### ISSUE TITLE
Memlog doesn't write any data with Chakracore version of Node, causing a crash when trying to create a graph

### ISSUE THREAD

**Issue by yweijiang** [Node-DC/Node-DC-EIS#12] opened 2017-03-09 21:05 UTC
Chakracore has missing memloginfo, which causes the attempt to write the memlog csv to fail because of mismatched array sizes. This causes a crash in the logging when the client attempts to read the memlog and create a graph because the file is empty.

**Comment by uttampawar** [comment] 2017-05-09 00:25
@yweijiang Would you like to submit a PR?

**Comment by yweijiang** [comment] 2017-05-09 00:34
We didn't want to submit a PR to avoid any kind of licensing issues before, and like I said in the other reply I sent a copy of the fixes to you and Priyanka in March. If you lost that copy I could send it again, but otherwise you should have the necessary fixes for this.

**Comment by uttampawar** [comment] 2017-06-13 15:39
Possible duplicate of https://github.com/Node-DC/Node-DC-EIS/issues/8

**Comment by uttampawar** [comment] 2017-07-05 23:57
Fixed upstream.

**Closed as completed by uttampawar** 2017-07-05 23:57 UTC
Labels: duplicate
